############################
## MODULES
############################

hugoVersion:
  extended: true
imports:
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-bootstrap/v5
    disable: false
  - path: github.com/privatemaker/headless-cms
    disable: false
